### ISSUE TITLE
Help about to prepare  "selections.pkl"  file

### ISSUE THREAD

**Issue by mksarker** [Yussef93/FewShotCellSegmentation#1]
Hi,

Thanks for the code. I am trying to training with my own datasets. 
Could you please help me with how you prepare the "selections.pkl"  file.

Thanks
Mostafa

**Comment by Yussef93** [comment]
hello, 

selections.pkl file is meant for fine-tuning on the same selections from the target dataset in listed in the experiments, so if you want to use your own datasets you'll need to produce your own selections. sorry for the delay

regards
